version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "8001:8000"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ../app/:/app/

volumes:
  postgres_data: